// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:Example.CleanArchitecture.UnitTests.Fixtures.Commands.CreateProductFixture.GenerateInvalidHandler(Example.CleanArchitecture.Application.Commands.CreateProduct.CreateProductCommand,System.Boolean,System.Boolean)~Example.CleanArchitecture.Application.Commands.CreateProduct.CreateProductCommandHandler")]
[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:Example.CleanArchitecture.UnitTests.Fixtures.Commands.CreateProductFixture.GenerateCommandFromEntity(Example.CleanArchitecture.Core.Entities.Product)~Example.CleanArchitecture.Application.Commands.CreateProduct.CreateProductCommand")]
[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:Example.CleanArchitecture.UnitTests.Fixtures.Commands.CreateProductFixture.GenerateValidHandler(Example.CleanArchitecture.Application.Commands.CreateProduct.CreateProductCommand,Example.CleanArchitecture.Core.Entities.Product,Example.CleanArchitecture.Application.ViewModels.ProductViewModel)~Example.CleanArchitecture.Application.Commands.CreateProduct.CreateProductCommandHandler")]
[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:Example.CleanArchitecture.UnitTests.Fixtures.Queries.GetProductByIdFixture.GenerateInvalidHandler~Example.CleanArchitecture.Application.Queries.GetProductById.GetProductByIdQueryHandler")]
[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:Example.CleanArchitecture.UnitTests.Fixtures.Queries.GetProductByIdFixture.GenerateValidHandler(Example.CleanArchitecture.Core.Entities.Product,Example.CleanArchitecture.Application.ViewModels.ProductViewModel)~Example.CleanArchitecture.Application.Queries.GetProductById.GetProductByIdQueryHandler")]
